//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDKAReservasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_Status
    {
        public tblM_Status()
        {
            this.tblM_Ruangan = new HashSet<tblM_Ruangan>();
        }
    
        public int Status_PK { get; set; }
        public string NamaStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<tblM_Ruangan> tblM_Ruangan { get; set; }
    }
}
